import { MetadataRoute } from "next";

/**
 * The installed-app entry.
 *
 * One icon, honestly described. This used to declare `/logo-icon.png` twice, as
 * 192x192 and as 512x512, and that file is 59x44 — so an install got the navbar
 * wordmark stretched into a square, and Chrome, which requires a real icon of at
 * least 192px, was within its rights to withhold the install prompt entirely.
 *
 * `/icon` is generated by `app/icon.tsx` at a true 512x512, which satisfies both
 * the minimum and the maskable safe zone, so one entry covers what two wrong
 * ones did not.
 *
 * `theme_color` matches the `viewport.themeColor` in the root layout. Two
 * different values meant the splash screen and the browser chrome disagreed.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Aangan Rooms",
    short_name: "Aangan",
    description: "Built in Kolhapur. Every room visited in person. No brokerage from students.",
    start_url: "/",
    display: "standalone",
    background_color: "#ffffff",
    theme_color: "#fa5a5a",
    icons: [
      {
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
